# Generated by Django 4.1.1 on 2022-10-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=30, null=True)),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('mobile', models.CharField(default='', max_length=30, null=True)),
                ('name', models.CharField(default='', max_length=30, null=True)),
                ('education', models.CharField(default='', max_length=30, null=True)),
            ],
        ),
    ]
