# Generated by Django 4.1.2 on 2022-11-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='training',
            field=models.BooleanField(default=False),
        ),
    ]
