# Generated by Django 4.2 on 2023-06-07 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_training_training'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Freesession',
        ),
        migrations.DeleteModel(
            name='Internship',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
